spring:
  application:
    name: file-server
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    com.rudy.file: ${SPRING_LOG_LEVEL:info}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    config-url: /api/file/v3/api-docs/swagger-config
    url: /api/file/v3/api-docs

url:
  auth-server: ${AUTH_SERVER}